# Site settings
title: DentistSmile | Dental Jekyll Theme
description: "A responsive Jekyll theme for dental clinics."
baseurl: "maxguesthouse.github.io" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Max Paying Guest House
    hero_description: Home away from home.

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 098374 12086
    emergency: Please see above
    email: maxpayingguest@gmail.com
    address: 63 MMIG Shaheed Nagar, Agra, 282001 Agra, Uttar Pradesh - India

# Opening hours
monday_friday: 06:00 – 22:30
saturday: 06:00 – 23:30
sunday: 07:00 – 00:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: 63 MMIG Shaheed Nagar, Agra, 282001 Agra, Uttar Pradesh - India
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com/max1702pg
# twitter: http://twitter.com
# instagram: http://instagram.com
# youtube: http://youtube.com
# skype: skype:obaez_design?userinfo
feed: yes

# Footer
Made With Love from <a href = "marketingbh.com">Marketing BH </a>

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
